project:
  type: website
  output-dir: docs

website:
  title: "mueang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css




